// app/api/avengers/route.js
export async function GET(request) {
  const avengers = [
    {
      name: 'Tony Stark',
      alias: 'Iron Man',
      powers: ['Genius intellect', 'Powered armor suit'],
      abilities: ['Flight', 'Superhuman strength', 'Energy repulsors'],
      relations: {
        team: ['Avengers'],
        significantOther: 'Pepper Potts',
        allies: ['James Rhodes', 'Bruce Banner'],
      },
    },
    {
      name: 'Steve Rogers',
      alias: 'Captain America',
      powers: ['Super soldier serum', 'Enhanced strength'],
      abilities: ['Expert tactician', 'Shield mastery', 'Leadership'],
      relations: {
        team: ['Avengers', 'Howling Commandos'],
        allies: ['Bucky Barnes', 'Sam Wilson'],
      },
    },
    {
      name: 'Thor Odinson',
      alias: 'Thor',
      powers: ['God of Thunder', 'Superhuman strength'],
      abilities: ['Mjolnir control', 'Lightning manipulation', 'Flight'],
      relations: {
        family: ['Odin (father)', 'Loki (brother)'],
        team: ['Avengers', 'Asgardians'],
      },
    },
    {
      name: 'Bruce Banner',
      alias: 'Hulk',
      powers: ['Gamma radiation transformation'],
      abilities: ['Superhuman strength', 'Regeneration', 'Leaping'],
      relations: {
        team: ['Avengers'],
        allies: ['Tony Stark', 'Natasha Romanoff'],
      },
    },
    {
      name: 'Natasha Romanoff',
      alias: 'Black Widow',
      powers: ['Peak human condition'],
      abilities: ['Master spy', 'Martial arts', 'Weapons expert'],
      relations: {
        team: ['Avengers', 'S.H.I.E.L.D.'],
        allies: ['Clint Barton', 'Steve Rogers'],
      },
    },
    {
      name: 'Clint Barton',
      alias: 'Hawkeye',
      powers: ['Peak human accuracy'],
      abilities: ['Master archer', 'Hand-to-hand combat', 'Trick arrows'],
      relations: {
        team: ['Avengers', 'S.H.I.E.L.D.'],
        family: ['Laura Barton (wife)'],
        allies: ['Natasha Romanoff'],
      },
    },
    {
      name: 'Peter Parker',
      alias: 'Spider-Man',
      powers: ['Spider physiology'],
      abilities: ['Wall-crawling', 'Web-shooting', 'Spider-sense'],
      relations: {
        team: ['Avengers'],
        family: ['May Parker (aunt)'],
        allies: ['Tony Stark'],
      },
    },
    {
      name: "T'Challa",
      alias: 'Black Panther',
      powers: ['Heart-shaped herb enhancement'],
      abilities: ['Superhuman senses', 'Vibranium suit', 'Leadership'],
      relations: {
        team: ['Avengers'],
        family: ["T'Chaka (father)"],
        title: 'King of Wakanda',
      },
    },
    {
      name: 'Carol Danvers',
      alias: 'Captain Marvel',
      powers: ['Cosmic energy manipulation'],
      abilities: ['Flight', 'Energy blasts', 'Super strength'],
      relations: {
        team: ['Avengers', 'Starforce'],
        allies: ['Nick Fury', 'Maria Rambeau'],
      },
    },
    {
      name: 'Stephen Strange',
      alias: 'Doctor Strange',
      powers: ['Master of Mystic Arts'],
      abilities: ['Magic spells', 'Time manipulation', 'Astral projection'],
      relations: {
        team: ['Avengers', 'Masters of the Mystic Arts'],
        allies: ['Wong'],
      },
    },
    // Adding 20 more Avengers
    {
      name: 'Sam Wilson',
      alias: 'Falcon',
      powers: ['Flight suit'],
      abilities: ['Aerial combat', 'Military training'],
      relations: { team: ['Avengers'], allies: ['Steve Rogers'] },
    },
    {
      name: 'Wanda Maximoff',
      alias: 'Scarlet Witch',
      powers: ['Chaos magic'],
      abilities: ['Reality warping', 'Telekinesis'],
      relations: { team: ['Avengers'], family: ['Pietro Maximoff (brother)'] },
    },
    {
      name: 'Pietro Maximoff',
      alias: 'Quicksilver',
      powers: ['Super speed'],
      abilities: ['Enhanced reflexes', 'Rapid healing'],
      relations: { team: ['Avengers'], family: ['Wanda Maximoff (sister)'] },
    },
    {
      name: 'James Rhodes',
      alias: 'War Machine',
      powers: ['Powered armor suit'],
      abilities: ['Flight', 'Military tactics'],
      relations: { team: ['Avengers'], allies: ['Tony Stark'] },
    },
    {
      name: 'Scott Lang',
      alias: 'Ant-Man',
      powers: ['Size manipulation'],
      abilities: ['Pym Particles mastery', 'Insect communication'],
      relations: { team: ['Avengers'], family: ['Cassie Lang (daughter)'] },
    },
    {
      name: 'Hope van Dyne',
      alias: 'Wasp',
      powers: ['Size manipulation'],
      abilities: ['Flight', 'Bio-energy blasts'],
      relations: { team: ['Avengers'], family: ['Hank Pym (father)'] },
    },
    {
      name: 'Vision',
      alias: 'Vision',
      powers: ['Mind Stone enhancement'],
      abilities: ['Density control', 'Flight', 'Energy beams'],
      relations: { team: ['Avengers'], significantOther: 'Wanda Maximoff' },
    },
    {
      name: 'Nick Fury',
      alias: 'Nick Fury',
      powers: ['Peak human condition'],
      abilities: ['Espionage', 'Leadership', 'Tactical genius'],
      relations: { team: ['Avengers', 'S.H.I.E.L.D.'] },
    },
    {
      name: 'Bucky Barnes',
      alias: 'Winter Soldier',
      powers: ['Super soldier serum'],
      abilities: ['Bionic arm', 'Combat mastery'],
      relations: { team: ['Avengers'], allies: ['Steve Rogers'] },
    },
    {
      name: 'Hank Pym',
      alias: 'Ant-Man (original)',
      powers: ['Size manipulation'],
      abilities: ['Pym Particles creator', 'Genius intellect'],
      relations: { team: ['Avengers'], family: ['Hope van Dyne (daughter)'] },
    },
    {
      name: 'Janet van Dyne',
      alias: 'Wasp (original)',
      powers: ['Size manipulation'],
      abilities: ['Flight', 'Bio-energy blasts'],
      relations: { team: ['Avengers'], family: ['Hope van Dyne (daughter)'] },
    },
    {
      name: 'Monica Rambeau',
      alias: 'Spectrum',
      powers: ['Energy transformation'],
      abilities: ['Light manipulation', 'Flight'],
      relations: { team: ['Avengers'], allies: ['Carol Danvers'] },
    },
    {
      name: 'Marc Spector',
      alias: 'Moon Knight',
      powers: ['Moon god enhancement'],
      abilities: ['Enhanced strength', 'Martial arts'],
      relations: { team: ['Avengers'] },
    },
    {
      name: 'Jennifer Walters',
      alias: 'She-Hulk',
      powers: ['Gamma radiation transformation'],
      abilities: ['Super strength', 'Legal expertise'],
      relations: { team: ['Avengers'], family: ['Bruce Banner (cousin)'] },
    },
    {
      name: 'Matt Murdock',
      alias: 'Daredevil',
      powers: ['Enhanced senses'],
      abilities: ['Acrobatics', 'Martial arts', 'Legal expertise'],
      relations: { team: ['Avengers', 'Defenders'] },
    },
    {
      name: 'Luke Cage',
      alias: 'Power Man',
      powers: ['Unbreakable skin'],
      abilities: ['Super strength', 'Combat skills'],
      relations: { team: ['Avengers', 'Defenders'] },
    },
    {
      name: 'Danny Rand',
      alias: 'Iron Fist',
      powers: ['Chi manipulation'],
      abilities: ['Martial arts mastery', 'Healing'],
      relations: { team: ['Avengers', 'Defenders'] },
    },
    {
      name: 'Jessica Jones',
      alias: 'Jewel',
      powers: ['Super strength'],
      abilities: ['Investigation', 'Flight (limited)'],
      relations: { team: ['Avengers', 'Defenders'] },
    },
    {
      name: 'Kamala Khan',
      alias: 'Ms. Marvel',
      powers: ['Polymorphing'],
      abilities: ['Shape-shifting', 'Size alteration'],
      relations: { team: ['Avengers'], allies: ['Carol Danvers'] },
    },
    {
      name: 'Shang-Chi',
      alias: 'Shang-Chi',
      powers: ['Peak human condition'],
      abilities: ['Martial arts mastery', 'Weapon proficiency'],
      relations: { team: ['Avengers'] },
    },
  ];

  return Response.json({
    status: 'success',
    count: avengers.length,
    data: avengers,
  });
}
