// app/api/avengers/route.js
export async function GET(request) {
  const avengers = [
    {
      id: 1,
      name: 'Tony Stark',
      alias: 'Iron Man',
      powers: ['Genius intellect', 'Powered armor suit'],
      abilities: ['Flight', 'Superhuman strength', 'Energy repulsors'],
      relations: {
        team: ['Avengers'],
        significantOther: 'Pepper Potts',
        allies: ['James Rhodes', 'Bruce Banner'],
      },
    },
    {
      id: 2,
      name: 'Steve Rogers',
      alias: 'Captain America',
      powers: ['Super soldier serum', 'Enhanced strength'],
      abilities: ['Expert tactician', 'Shield mastery', 'Leadership'],
      relations: {
        team: ['Avengers', 'Howling Commandos'],
        allies: ['Bucky Barnes', 'Sam Wilson'],
      },
    },
    {
      id: 3,
      name: 'Thor Odinson',
      alias: 'Thor',
      powers: ['God of Thunder', 'Superhuman strength'],
      abilities: ['Mjolnir control', 'Lightning manipulation', 'Flight'],
      relations: {
        family: ['Odin (father)', 'Loki (brother)'],
        team: ['Avengers', 'Asgardians'],
      },
    },
    {
      id: 4,
      name: 'Bruce Banner',
      alias: 'Hulk',
      powers: ['Gamma radiation transformation'],
      abilities: ['Superhuman strength', 'Regeneration', 'Leaping'],
      relations: {
        team: ['Avengers'],
        allies: ['Tony Stark', 'Natasha Romanoff'],
      },
    },
    {
      id: 5,
      name: 'Natasha Romanoff',
      alias: 'Black Widow',
      powers: ['Peak human condition'],
      abilities: ['Master spy', 'Martial arts', 'Weapons expert'],
      relations: {
        team: ['Avengers', 'S.H.I.E.L.D.'],
        allies: ['Clint Barton', 'Steve Rogers'],
      },
    },
    {
      id: 6,
      name: 'Clint Barton',
      alias: 'Hawkeye',
      powers: ['Peak human accuracy'],
      abilities: ['Master archer', 'Hand-to-hand combat', 'Trick arrows'],
      relations: {
        team: ['Avengers', 'S.H.I.E.L.D.'],
        family: ['Laura Barton (wife)'],
        allies: ['Natasha Romanoff'],
      },
    },
    {
      id: 7,
      name: 'Peter Parker',
      alias: 'Spider-Man',
      powers: ['Spider physiology'],
      abilities: ['Wall-crawling', 'Web-shooting', 'Spider-sense'],
      relations: {
        team: ['Avengers'],
        family: ['May Parker (aunt)'],
        allies: ['Tony Stark'],
      },
    },
    {
      id: 8,
      name: "T'Challa",
      alias: 'Black Panther',
      powers: ['Heart-shaped herb enhancement'],
      abilities: ['Superhuman senses', 'Vibranium suit', 'Leadership'],
      relations: {
        team: ['Avengers'],
        family: ["T'Chaka (father)"],
        title: 'King of Wakanda',
      },
    },
    {
      id: 9,
      name: 'Carol Danvers',
      alias: 'Captain Marvel',
      powers: ['Cosmic energy manipulation'],
      abilities: ['Flight', 'Energy blasts', 'Super strength'],
      relations: {
        team: ['Avengers', 'Starforce'],
        allies: ['Nick Fury', 'Maria Rambeau'],
      },
    },
    {
      id: 10,
      name: 'Stephen Strange',
      alias: 'Doctor Strange',
      powers: ['Master of Mystic Arts'],
      abilities: ['Magic spells', 'Time manipulation', 'Astral projection'],
      relations: {
        team: ['Avengers', 'Masters of the Mystic Arts'],
        allies: ['Wong'],
      },
    },
    // Adding 20 more Avengers
    {
      id: 11,
      name: 'Sam Wilson',
      alias: 'Falcon',
      powers: ['Flight suit'],
      abilities: ['Aerial combat', 'Military training'],
      relations: { team: ['Avengers'], allies: ['Steve Rogers'] },
    },
    {
      id: 12,
      name: 'Wanda Maximoff',
      alias: 'Scarlet Witch',
      powers: ['Chaos magic'],
      abilities: ['Reality warping', 'Telekinesis'],
      relations: { team: ['Avengers'], family: ['Pietro Maximoff (brother)'] },
    },
    {
      id: 13,
      name: 'Pietro Maximoff',
      alias: 'Quicksilver',
      powers: ['Super speed'],
      abilities: ['Enhanced reflexes', 'Rapid healing'],
      relations: { team: ['Avengers'], family: ['Wanda Maximoff (sister)'] },
    },
    {
      id: 14,
      name: 'James Rhodes',
      alias: 'War Machine',
      powers: ['Powered armor suit'],
      abilities: ['Flight', 'Military tactics'],
      relations: { team: ['Avengers'], allies: ['Tony Stark'] },
    },
    {
      id: 15,
      name: 'Scott Lang',
      alias: 'Ant-Man',
      powers: ['Size manipulation'],
      abilities: ['Pym Particles mastery', 'Insect communication'],
      relations: { team: ['Avengers'], family: ['Cassie Lang (daughter)'] },
    },
    {
      id: 16,
      name: 'Hope van Dyne',
      alias: 'Wasp',
      powers: ['Size manipulation'],
      abilities: ['Flight', 'Bio-energy blasts'],
      relations: { team: ['Avengers'], family: ['Hank Pym (father)'] },
    },
    {
      id: 17,
      name: 'Vision',
      alias: 'Vision',
      powers: ['Mind Stone enhancement'],
      abilities: ['Density control', 'Flight', 'Energy beams'],
      relations: { team: ['Avengers'], significantOther: 'Wanda Maximoff' },
    },
    {
      id: 18,
      name: 'Nick Fury',
      alias: 'Nick Fury',
      powers: ['Peak human condition'],
      abilities: ['Espionage', 'Leadership', 'Tactical genius'],
      relations: { team: ['Avengers', 'S.H.I.E.L.D.'] },
    },
    {
      id: 19,
      name: 'Bucky Barnes',
      alias: 'Winter Soldier',
      powers: ['Super soldier serum'],
      abilities: ['Bionic arm', 'Combat mastery'],
      relations: { team: ['Avengers'], allies: ['Steve Rogers'] },
    },
    {
      id: 20,
      name: 'Hank Pym',
      alias: 'Ant-Man (original)',
      powers: ['Size manipulation'],
      abilities: ['Pym Particles creator', 'Genius intellect'],
      relations: { team: ['Avengers'], family: ['Hope van Dyne (daughter)'] },
    },
  ];

  return Response.json(avengers);
}
